src/lostpetfinder/pets/urls.py
"""
URL routing of Pets application
"""
from django.conf.urls import url
from .views import (
    PetListView,
    PetDetailView,
    PetCreateView,
    PetUpdateView,
    PetDeleteView,
)

app_name = 'pets'
urlpatterns = [
    url(r'^$', PetListView.as_view(), name='list'),
    url(r'^register/$', PetCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PetUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PetDeleteView.as_view(), name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', PetDetailView.as_view(), name='detail'),
]

src/lostpetfinder/templates/snippets/form.html
{% comment %}
  File name: form.html
  Description: Form template used to render to HTML form.
{% endcomment %}

{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
  <div class="form-group">
    {% render_field field.label %}
    {% render_field field class=field|input_class placeholder=field.label %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div> <!-- end form-group -->
{% endfor %}

src/lostpetfinder/templates/snippets/nav.html
<!-- NAVIGATION BAR WITH BOOTSTRAP 4.0.0-beta -->
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #283593;">
  <a class="navbar-brand" href="{% url 'home' %}">Lost Pet Finder</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lost-pets' %}">Lost Pets</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'reunited-pets' %}">Reunited Pets</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search-pets' %}" method="GET" role="search">
      <input class="form-control mr-sm-2" type="text" placeholder="Search pet..." aria-label="Search" name="q" value="{{ request.GET.q }}">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">{{ user.username }}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Login</a>
        </li>
      {% endif %}
      <li class="nav-item dropdown hidden-xs-down">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-nav fa-user" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <h6 class="dropdown-header">Account</h6>
          {% if user.is_authenticated and user.is_superuser %}
            <a class="dropdown-item" href="{% url 'users_list' %}">Users</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'profile' %}"><i class="fa fa-nav fa-user" aria-hidden="true"></i>&nbsp;My Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Logout</a>
          {% elif user.is_authenticated and not user.is_superuser %}
            <a class="dropdown-item" href="{% url 'pets:list' %}">My Pets</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'profile' %}"><i class="fa fa-nav fa-user" aria-hidden="true"></i>&nbsp;My Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Logout</a>
          {% else %}
            <a class="dropdown-item"  href="{% url 'register' %}"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;Register</a>
            <a class="dropdown-item" href="{% url 'login' %}"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Login</a>
          {% endif %}
        </div><!-- /.dropdown-menu dropdown-menu-right -->
      </li>
    </ul>
  </div> <!-- /.collapse navbar-collapse -->
</nav>

src/lostpetfinder/templates/snippets/navigation_bar.html
<!-- NAVIGATION BAR WITH BOOTSTRAP 4.0.0-beta -->
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #283593;">
  <a class="navbar-brand" href="{% url 'home' %}">Lost Pet Finder</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lost-pets' %}">Lost Pets</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'reunited-pets' %}">Reunited Pets</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search-pets' %}" method="GET" role="search">
      <input class="form-control mr-sm-2" type="text" placeholder="Search pet..." aria-label="Search" name="q" value="{{ request.GET.q }}">
      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav navbar-right">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">{{ user.username }}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Login</a>
        </li>
      {% endif %}
      <li class="nav-item dropdown hidden-xs-down">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-nav fa-user" aria-hidden="true"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <h6 class="dropdown-header">Account</h6>
          {% if user.is_authenticated and user.is_superuser %}
            <a class="dropdown-item" href="{% url 'users_list' %}">Users</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'profile' %}"><i class="fa fa-nav fa-user" aria-hidden="true"></i>&nbsp;My Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Logout</a>
          {% elif user.is_authenticated and not user.is_superuser %}
            <a class="dropdown-item" href="{% url 'pets:list' %}">My Pets</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'profile' %}"><i class="fa fa-nav fa-user" aria-hidden="true"></i>&nbsp;My Profile</a>
            <a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Logout</a>
          {% else %}
            <a class="dropdown-item"  href="{% url 'register' %}"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;Register</a>
            <a class="dropdown-item" href="{% url 'login' %}"><i class="fa fa-power-off" aria-hidden="true"></i>&nbsp;Login</a>
          {% endif %}
        </div><!-- /.dropdown-menu dropdown-menu-right -->
      </li>
    </ul>
  </div> <!-- /.collapse navbar-collapse -->
</nav>

src/lostpetfinder/templates/snippets/page_navigation.html
{% comment %}
  Page navigation template used with Class Base View for browsing list of objects.
  Reference: https://simpleisbetterthancomplex.com/tutorial/2016/08/03/how-to-paginate-with-django.html
{% endcomment%}

{% if is_paginated %}
  <nav aria-label="Page Nagivation">
    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
      {% else %}
        <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
      {% endif %}
      {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
      {% else %}
        <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

src/lostpetfinder/templates/snippets/sidebar.html
<ul>
    <li>Item 1</li>
    <li>Item 2</li>
    <li>Item 3</li>
</ul>