src/lostpetfinder/pets/api/urls.py
from django.conf.urls import url

from .views import (
    PetListAPIView,
    PetDetailAPIView,
    PetCreateAPIView,
    PetRetrieveUpdateAPIView,
    PetDeleteAPIView,
)

urlpatterns = [
    url(r'^$', PetListAPIView.as_view(), name='list'),
    url(r'^register/$', PetCreateAPIView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PetDetailAPIView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PetRetrieveUpdateAPIView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PetDeleteAPIView.as_view(), name='delete'),
]

src/lostpetfinder/pets/urls.py
"""
URL routing of Pets application
"""
from django.conf.urls import url
from .views import (
    PetListView,
    PetDetailView,
    PetCreateView,
    PetUpdateView,
    PetDeleteView,
)

app_name = 'pets'
urlpatterns = [
    url(r'^$', PetListView.as_view(), name='list'),
    url(r'^register/$', PetCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PetUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PetDeleteView.as_view(), name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', PetDetailView.as_view(), name='detail'),
]

src/lostpetfinder/pets/forms.py
"""
File name: forms.py
Description: Django form classes which are used with 'pets' application.
"""
from django import forms
from pets.models import Pet

class PetRegistrationForm(forms.ModelForm):
    """
    Form definition which is used to to register and update pet.
    """
    class Meta:
        model = Pet
        fields = [
            'name',
            'location',
            'pet_type',
            'colour',
            'age',
            'size',
            'gender',
            'desexed',
            'collar',
            'microchipped',
            'microchipped_no',
            'missing_date',
            'status',
            'description',
            'pet_image',
        ]
        widgets = {
            'missing_date': forms.SelectDateWidget,
        }

    def __init__(self, user=None, *args, **kwargs):
        """
        Passing key word argurments to PetRegistrationForm
        """
        super(PetRegistrationForm, self).__init__(*args, **kwargs)

src/lostpetfinder/pets/api/views.py
from django.db.models import Q # filter using operators '&' or '|'

from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)
from rest_framework.generics import (
    ListAPIView,
    CreateAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView,
    DestroyAPIView,
)

from rest_framework.permissions import (
    IsAuthenticated,
    AllowAny,
    IsAuthenticatedOrReadOnly,
)

# Custom permissions
from .permissions import IsOwnerOrReadOnly

from .serializers import (
    PetListSerializer,
    PetDetailSerializer,
    PetCreateUpdateSerializer,
)

from pets.models import Pet

class PetListAPIView(ListAPIView):
    """
    Get all pets
    """
    serializer_class = PetListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['status', 'name', 'location', 'pet_type']

    def get_queryset(self, *args, **kwargs):
        queryset_list = Pet.objects.all()
        query = self.request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(
                Q(status__icontains=query)|
                Q(name__icontains=query)|
                Q(location__icontains=query)|
                Q(pet_type__icontains=query)
            ).distinct()
        return queryset_list

class PetDetailAPIView(RetrieveAPIView):
    """
    Get specific pet details.
    """
    queryset = pets = Pet.objects.all()
    serializer_class = PetDetailSerializer
    lookup_field = 'slug'

class PetCreateAPIView(CreateAPIView):
    """
    Create a pet.
    """
    queryset = pets = Pet.objects.all()
    serializer_class = PetCreateUpdateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class PetRetrieveUpdateAPIView(RetrieveUpdateAPIView):
    """
    Update specific pet.
    """
    queryset = pets = Pet.objects.all()
    serializer_class = PetCreateUpdateSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    lookup_field = 'slug'

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

class PetDeleteAPIView(DestroyAPIView):
    """
    Delete specific pet.
    """
    queryset = pets = Pet.objects.all()
    serializer_class = PetDetailSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    lookup_field = 'slug'

src/lostpetfinder/pets/views.py
"""
Django views classes which are used to handle business domain of
the pets application.
"""
# Class base view mixins that verify current authenticated user
from django.contrib.auth.mixins import LoginRequiredMixin

from django.db.models import Q # filter using operators '&' or '|'
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.core.urlresolvers import reverse, resolve

# Django generic class base views
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)

from pets.forms import PetRegistrationForm
from pets.models import Pet

class PetListView(ListView):
    """
    Get list of pets:
        GET /finder/pets: get pets owned by authenticated user.
        GET /pets: get pets with lost status.
        GET /reunited-pets: get pets with found status.
        GET pets/search/?q=[query]:
            search pets with status, pet type, pet name, and location
    """
    context_object_name = 'pets' # change default object_list to pets
    paginate_by = 6 # display 6 pets per page

    def get_queryset(self, *args, **kwargs):
        """
        Return a list of pets based on search filter
        """
        # get requested URL namespace
        url_name = resolve(self.request.path).url_name

        if(url_name == 'list'): # GET /finder/pets/ (refer to pets.urls)
            return Pet.objects.filter(owner=self.request.user)

        if(url_name == 'lost-pets'): # GET /pets
            return Pet.objects.filter(status__iexact='lost')

        if(url_name == 'reunited-pets'): # GET /reunited-pets
            return Pet.objects.filter(status__iexact='found')

        if(url_name == 'search-pets'): # GET /pets/search/?q=[query]
            # Exclude pet with registered status from search query
            # hide pet with 'Registered' status from public view
            queryset = Pet.objects.exclude(status__iexact='registered')

            query = self.request.GET.get('q')
            if query:
                search_list = queryset.filter(
                    Q(status__iexact=query)|
                    Q(name__icontains=query)|
                    Q(location__icontains=query)|
                    Q(pet_type__iexact=query)
                ).distinct()
                return search_list
            return queryset

    def get_context_data(self, *args, **kwargs):
        """
        Get context data of page
        """
        context = super(PetListView, self).\
            get_context_data(*args, **kwargs)

        # get requested URL namespace
        url_name = resolve(self.request.path).url_name
        title = 'My Pets' # default title to be 'My Pets'

        if(url_name == 'lost-pets'):
            title = 'Lost Pets'

        if(url_name == 'reunited-pets'):
            title = 'Found Pets'

        context['title'] = title
        return context

class PetDetailView(DetailView):
    """
    Get specific pet details
        GET /finder/pets/slug/
    """
    def get_queryset(self):
        """
        Get specific pet based on pet's slug
        """
        slug = self.kwargs.get('slug')
        return Pet.objects.filter(slug=slug)

    def get_context_data(self, *args, **kwargs):
        """
        Get context data for rendering 'pets/pet_detail.html'
        """
        slug = self.kwargs.get('slug')
        pet = Pet.objects.get(slug=slug)
        petLatLng = pet.get_geolocation_data() # get pet's geolocation from API

        context = super(PetDetailView, self).\
            get_context_data(*args, **kwargs)

        context['title'] = pet.name
        context['lat'] = petLatLng['lat'] # pet's latitude
        context['lng'] = petLatLng['lng'] # pet's longitude

        # Define bootstrap CSS classes for rendering
        # 'pets/pet_detail_data.html'base on pet's status
        if(pet.status.lower() == 'lost'):
            context['bt_badge_css'] = "badge-danger"
        if(pet.status.lower() == 'found'):
            context['bt_badge_css'] = "badge-primary"
        if(pet.status.lower() == 'registered'):
            context['bt_badge_css'] = "badge-warning"
        return context

class PetCreateView(LoginRequiredMixin, CreateView):
    """
    Pet registration
    POST /pets/register
    """
    form_class = PetRegistrationForm
    template_name = 'pets/pet_form.html'
    login_url = 'login' # Redirect to login url if not authenticated

    def get_queryset(self):
        """
        Get pets owned by the current authenticated user
        """
        return Pet.objects.filter(owner=self.request.user)

    def form_valid(self, form):
        """
        Form Validation
        """
        instance = form.save(commit=False)
        instance.owner = self.request.user # current authenticated user
        return super(PetCreateView, self).form_valid(form)

    def get_form_kwargs(self):
        """
        Return the key word argurments for instantiating the form
        """
        kwargs = super(PetCreateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        """
        Get context data for rendering a HTML page
        """
        context = super(PetCreateView, self).\
            get_context_data(*args, **kwargs)
        context['title'] = 'Pet Registration'
        return context

class PetUpdateView(LoginRequiredMixin, UpdateView):
    """
    Update specific pet
        POST /finder/pets/{slug-field}/edit/
    """
    form_class = PetRegistrationForm
    template_name = 'pets/pet_form.html'

    def get_queryset(self):
        """
        Get pets owned by the authenticated user
        """
        return Pet.objects.filter(owner=self.request.user)

    def get_form_kwargs(self):
        """
        Return the key word argurments for instantiating the form
        """
        kwargs = super(PetUpdateView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def get_context_data(self, *args, **kwargs):
        """
        Get context data for rendering a HTML page
        """
        slug = self.kwargs.get('slug')
        pet = Pet.objects.get(slug=slug)
        context = super(PetUpdateView, self).\
            get_context_data(*args, **kwargs)
        context['title'] = f'Edit {pet.pet_type}: {pet.name.upper()}'
        return context

class PetDeleteView(LoginRequiredMixin, DeleteView):
    """
    Delete specific pet
        POST /finder/pets/pets/delete
    """
    success_url = reverse_lazy('pets:list') # Return to pets list

    def get_queryset(self):
        """
        Get pets owned by the authenticated user
        """
        return Pet.objects.filter(owner=self.request.user)

    def get_context_data(self, *args, **kwargs):
        """
        Get context data for rendering HTML page
        """
        context = super(PetDeleteView, self).\
            get_context_data(*args, **kwargs)
        pet = Pet.objects.get(slug=self.kwargs.get('slug'))
        context['title'] = pet.name
        return context

src/lostpetfinder/pets/templates/pets/form.html
{% extends "base.html" %}

{% block head_title %}Lost Pet Registraion || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Lost Pet Registration</h1>
  <form method="POST">
    {% csrf_token %} <!-- Cross Site Request Forgery protection -->
    {{ form.as_p }}
  <button type="submit">Save</button>
</form>
{% endblock %}

src/lostpetfinder/pets/templates/pets/lostpet_create.html
{% extends "base.html" %}

{% block head_title %}Lost Pet Registraion || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Lost Pet Registration</h1>
  <form method="POST">
    {% csrf_token %} <!-- Cross Site Request Forgery protection -->
    {{ form.as_p }}
  <button type="submit">Register</button>
</form>
{% endblock %}

src/lostpetfinder/pets/templates/pets/lostpet_detail.html
{% extends "base.html" %}
{% block head_title %}Pets Details || {{ block.super }}{% endblock head_title %}
{% block content %}
  <h1>Pet Details</h1>
  <p><a href="{% url "pets:update" %}">Update your pet now</a></p>
  <h2>{{ object.name }} <small>{{ object.pet_type }}</small></h2>
  <p>{{ object.location }}</p>
  <p>{{ object.timestamp }}, updated {{ object.updated|timesince }} ago.</p>
{% endblock %}

src/lostpetfinder/pets/templates/pets/lostpet_list.html
{% extends "base.html" %}
{% block head_title %}Pets List || {{ block.super }}{% endblock head_title %}

{% block content %}
<h1>Pets List</h1>
<p><a href="{% url "pets:create" %}">Register your pet now</a></p>
<ul>
{% for obj in object_list %}
  <li><a href="{{ obj.get_absolute_url }}">{{ obj }}</a>
    {{ obj.location }} {{ obj.timestamp }} {{ obj.updated }}</li>
{% endfor %}
</ul>
{% endblock %}

src/lostpetfinder/pets/templates/pets/pet_confirm_delete.html
{% extends "base.html" %}

{% comment %}
  File name: pet_confirm_delete.html
  Description: the page is used to prompt user to confirm the deletion of
               the specific pet.
  Note: This comment block needs to be after {% extends ... %} template tag.
{% endcomment %}

{% block head_title %}{{ title }}|| {{ block.super }}{% endblock head_title %}

{% block content %}
  <h2 class="page-title">Remove listing of the <strong>{{ object.pet_type }}: {{ object.name }}</strong>!</h2>
  <form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to remove listing of the <strong>{{ object.pet_type }}: {{ object.name }}</strong>?</p>
    <button type="submit" class="btn btn-danger">
      <i class="fa fa-trash-o fa-lg"></i> Delete</button>
    <a class='btn btn-default' href="{% url 'pets:detail' object.slug %}">Cancel</a>
  </form>
{% endblock %}

src/lostpetfinder/pets/templates/pets/pet_detail.html
{% extends "base.html" %}

{% comment %}
  File name: pet_detail.html
  Description: the HTML file to display details of specific pet.
  URL: GET /finder/pets/{slug-field}/
  Note: this comment block needs to be after template tag {% extends ... %}.
{% endcomment %}

{% load static %}

{% block head_title %}{{ title }} || {{ block.super }}{% endblock head_title %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/pets.css' %}">
{% endblock %}

{% block content %}
  <!-- Display pet details -->
  {% include 'pets/pet_detail_data.html' %}
  <!-- End of pet details -->
  <!-- Display google map based on pet's location -->
  <div class="row">
    <div class="col">
      <div id="map" style="400px;height:400px;background:yellow"></div>
      <div id="petLat" value="{{ lat }}" hidden>{{ lat }}</div>
      <div id="petLng" value="{{ lng }}" hidden>{{ lng }}</div>
      {% block javascript %}
        <script src="{% static 'js/googlemap.js' %}"></script>
      {% endblock %}
    </div> <!-- /.col -->
  </div> <!-- /.row -->
  <!-- End of pet google map location -->
{% endblock %}

src/lostpetfinder/pets/templates/pets/pet_detail_data.html
{% comment %}
  File name: pet_detail_data.html
  Description: the partial HTML file to display information of specific pet.
               The file to be included within pet_detail.html file.
{% endcomment %}

<div class="row jumbotron">
  <div class="col-md-12">
    <h1 class="page-title">{{ title|upper }}</h1>
    <ul class="list-inline">
      <li class="list-inline-item badge badge-pill badge-primary">{{ object.pet_type }}</li>
      <li class="list-inline-item badge badge-pill badge-info">{{ object.location }}</li>
      <li class="list-inline-item badge badge-pill {{ bt_badge_css }}">{{ object.status }}</li>
      {% if user.is_authenticated and user == object.owner %}
        <li class="list-inline-item">
          <a class="btn btn-outline-primary btn-sm" href="{{ object.get_absolute_url }}edit/">
            <i class="fa fa-pencil fa-fw"></i> Edit</a>
        </li>
        <li class="list-inline-item">
          <a class="btn btn-outline-danger btn-sm" href="{{ object.get_absolute_url }}delete/">
            <i class="fa fa-trash-o fa-fw"></i> Delete</a>
        </li>
      {% endif %}
    </ul>
    <div class="row">
      <div class="col-md-4 details">
        {% ifequal object.status|lower "lost" %}
        <p><span class="badge badge-danger">Missing Date:</span> {{ object.missing_date|date:'D, d M Y' }}</p>
        {% endifequal %}
        {% ifequal object.status|lower "found" %}
        <p><span class="badge badge-info">Found Date:</span> {{ object.updated|date:'D, d M Y' }}</p>
        {% endifequal %}
        <p><span class="badge badge-info">Age:</span> {{ object.age }} years</p>
        <p><span class="badge badge-info">Gender:</span> {{ object.gender }}</p>
        <p><span class="badge badge-info">Desexed:</span> {{ object.desexed }}</p>
        <p><span class="badge badge-info">Description:</span> {{ object.description }}</p>
      </div> <!-- /.col-md-4 -->
      <div class="col-md-4 details">
        <p><span class="badge badge-info">Size:</span> {{ object.size }}</p>
        <p><span class="badge badge-info">Colour:</span> {{ object.colour }}</p>
        <p><span class="badge badge-info">Microchipped:</span> {{ object.microchipped }}</p>
        <p><span class="badge badge-info">Collar:</span> {{ object.collar }}</p>
      </div> <!-- /.col-md-4 -->
      <div class="col-md-4">
        {% if not object.pet_image %}
        <img src=http://placehold.it/360x360/>
        {% else %}
          <img src="{{ object.pet_image.url }}" height="auto" width="100%" />
        {% endif %}
      </div> <!-- /.col-md-4 -->
    </div> <!-- /.row -->
  </div> <!-- /.col-md-12 -->
</div> <!-- /.row jumbotron -->

src/lostpetfinder/pets/templates/pets/pet_form.html
{% extends "base.html" %}

{% comment %}
  File name: pet_form.html
  Description: This pet_form.html is used for creating, updating a pet.
{% endcomment %}

{% block head_title %}{{ title }} || {{ block.super }}{% endblock head_title %}

{% block content %}
  <form method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {% include 'snippets/form.html' %}
   	{% url 'pets:create' as register_url %}
	{% if request.get_full_path == register_url %}
  		<button type="submit" class="btn btn-primary">
        <i class="fa fa-paw"></i> Register your new pet</button>
  	{% else %}
  	  	<button type="submit" class="btn btn-primary">
          <i class="fa fa-paw"></i> Update</button>
	{% endif %}
    <a class='btn btn-default' href="{% url 'pets:list' %}">Cancel</a>
  </form>
{% endblock %}

src/lostpetfinder/pets/templates/pets/pet_list.html
{% extends "base.html" %}

{% comment %}
  File name: pet_list.html
  Description: the HTML file used to display a list of pets
               which are used for the views of lost/found pets and user's pets.
  Note: this comment block needs to be after the template tag {% extends ... %}.
{% endcomment %}

{% load static %}

{% block head_title %}{{ title }} || {{ block.super }}{% endblock head_title %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/pets.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">{{ title }}</h1>
<p><a class="btn btn-default" href="{% url "pets:create" %}">
  <i class="fa fa-paw"></i> Register your new pet</a></p>
<!-- Display list of pets in bootstrap card format -->
<div class="row py-2">
  {% for pet in pets %}
    <div class="col-xs-6 col-lg-4 py-2">
      <div class="card text-center">
        {% if not pet.pet_image %}
          <img class="card-img-top rounded-circle" src="#">
        {% else %}
          <img class="card-img-top rounded-circle" src="{{ pet.pet_image.url }}">
        {% endif %}
        <div class="card-body">
          <h4 class="card-title">{{ pet.name|upper }}</h4>
          <h6 class="card-subtitle mb-2 text-muted">{{ pet.pet_type }}</h6>
          <div class="card-text">
            {% ifequal pet.status|lower "lost" %}
              <p>Missing since
                <span class="badge badge-pill badge-danger">
                  {{ pet.missing_date|date:'D, d M Y' }}</span></p>
            {% endifequal %}
            {% ifequal pet.status|lower "found" %}
              <p>Found on
                <span class="badge badge-pill badge-primary">
                  {{ pet.updated|date:'D, d M Y' }}</span></p>
            {% endifequal %}
            {% ifequal pet.status|lower "registered" %}
              <p>Status
                <span class="badge badge-pill badge-info">
                  {{ pet.status|upper }}</span></p>
            {% endifequal %}
            <p>From
              <span class="badge badge-pill badge-info">
                {{ pet.location }}</span></p>
          </div> <!-- /.card-text -->
          <p><a class="btn btn-outline-primary btn-sm"
            href="{{ pet.get_absolute_url }}"
            role="button">More Info &raquo;</a></p>
        </div> <!-- /.card-body -->
      </div> <!-- /.card text-center -->
    </div> <!-- /.col-xs-6 col-lg-4 py-2 -->
  {% endfor %}
</div> <!-- /.row py-2 -->
<!-- end displaying list of pets in bootstrap card format -->
<div class="d-flex justify-content-end">
  {% include 'snippets/page_navigation.html' %}
</div>
{% endblock %}